# Generated by Django 2.2.10 on 2021-01-31 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='public_key',
            field=models.CharField(default='null', max_length=1000),
        ),
    ]
